#!/system/bin/sh

IF_G5=$(sed 's/G5//g' <<< "$1")

mount -o rw,remount /
mount -o rw,remount /system

cp /data/media/0/Zacharee1Mods/"$1".apk /system/priv-app/"$IG_G5"/"$IF_G5".apk
chmod 0644 /system/priv-app/"$IF_G5"/"$IF_G5".apk