#!/system/bin/sh

echo "<font color='#FF0000'>##########################################</font>"
echo "<font color='#00FF00'>$(date)</font>"
echo "<font color='#0000FF'>Installing: '$1'</font>"

IF_G5=$(printf '%s\n' "$1" | sed 's/G5//g')

echo " "
mount -vo rw,remount /
mount -vo rw,remount /system

echo " "
cp -v /data/media/0/Zacharee1Mods/"$1".jar /system/framework/"$IF_G5".jar
chmod -v 0644 /system/framework/"$IF_G5".jar

echo "<font color='#FF0000'>##########################################</font>"
echo "\n"