#!/system/bin/sh

echo "##########################################"
echo "$(date)"
echo "Installing: '$1'"

echo " "
mount -vo rw,remount /
mount -vo rw,remount /system

echo " "
cp -v /data/media/0/Zacharee1Mods/"$1".apk /system/app/"$1"/"$1".apk
chmod -v 0644 /system/app/"$1"/"$1".apk

echo "##########################################"
echo "\n"