#!/system/bin/sh

echo "<font color='#FF0000'>##########################################</font>"
echo "<font color='#00FF00'>$(date)</font>"
echo "<font color='#0000FF'>Installing: '$1'</font>"

echo " "
mount -vo rw,remount /
mount -vo rw,remount /system

echo " "
cp -v /data/media/0/Zacharee1Mods/"$1".apk /system/app/"$1"/"$1".apk
chmod -v 0644 /system/app/"$1"/"$1".apk

echo "<font color='#FF0000'>##########################################</font>"
echo "\n"