#!/system/bin/sh


echo "<font color='#FF0000'>##########################################</font>"
echo "<font color='#00FF00'>$(date)</font>"
echo "<font color='#0000FF'>Installing: 3Minit Resources</font>"

echo " "
busybox mount -vo rw,remount /
busybox mount -vo rw,remount /system

BAT="3MinitBatterySettings"
BATRES="MinitBatteryResources"
CLOCK="3MinitClock"

echo " "
busybox mkdir -v /data/media/0/Zacharee1Mods/mod
busybox mkdir -v /system/app/"$BAT"
busybox mkdir -v /system/app/"$CLOCK"
busybox mkdir -v /system/app/"$BATRES"

echo " "
busybox unzip -v /data/media/0/Zacharee1Mods/"$1".zip
busybox unzip -od /data/media/0/Zacharee1Mods/mod/ /data/media/0/Zacharee1Mods/"$1".zip

echo " "
busybox cp -v /data/media/0/Zacharee1Mods/mod/"$BAT".apk /system/app/"$BAT"/"$BAT".apk
busybox cp -v /data/media/0/Zacharee1Mods/mod/"$BATRES".apk /system/app/"$BATRES"/"$BATRES".apk
busybox cp -v /data/media/0/Zacharee1Mods/mod/"$CLOCK".apk /system/app/"$CLOCK"/"$CLOCK".apk

echo " "
busybox chmod -v 0755 /system/app/"$BAT"/
busybox chmod -v 0755 /system/app/"$BATRES"/
busybox chmod -v 0755 /system/app/"$CLOCK"/

echo " "
busybox chmod -v 0644 /system/app/"$BAT"/"$BAT".apk
busybox chmod -v 0644 /system/app/"$BATRES"/"$BATRES".apk
busybox chmod -v 0644 /system/app/"$CLOCK"/"$CLOCK".apk

echo "<font color='#FF0000'>##########################################</font>"
echo "\n"